### ISSUE TITLE
No support for DiscordShardedClient?

### ISSUE THREAD

**Issue by Erlite** [PassiveModding/Discord.Addons.Interactive#3]
It looks like InteractiveService has no support for DiscordShardedClient. Do you plan to add it?

**Comment by PassiveModding** [comment]
it's very much possible to create your own simply by modifying the interactive service. In-fact it's already present in one of my other bots.
https://github.com/PassiveModding/Passive-BOT/blob/master/PassiveBOT/Context/InteractiveService.cs

**Comment by PassiveModding** [comment]
I have now added official support for it https://github.com/PassiveModding/Discord.Addons.Interactive/commit/4c8a3dfce38c9eb0c1fb9a3246b5081fae493d9c
